### PR TITLE
Add scripts to build miso with 8.4

### PR DESCRIPTION
**Pull request by dmjio**
cc @cocreature @FPtje

### CODE REVIEW

**Comment by dmjio** [comment]
cc @tysonzero

**Comment by dmjio** [comment]
Still suffers from https://github.com/ghcjs/ghcjs/issues/666, leaving this open until it's fixed.

**Comment by dmjio** [comment]
@FPtje's patch fixes the build. https://github.com/ghcjs/ghcjs/issues/710

**Comment by FPtje** [comment]
Check this out:
https://github.com/FPtje/miso-isomorphic-example/blob/93470ca431d759168facfac5234bbc5e4619e72c/default.nix

The version of nixpkgs in that file (and later versions of nixpkgs 18.09) have the right fixes for the above mentioned issues. There are still some overrides to account for https://github.com/ghcjs/ghcjs/issues/711.

It means you can remove the patch and use `ghc844` instead of `ghc843`.

**Comment by dmjio** [comment]
Closing in favor of #493 (bumps to use `ghcjs863`)

**Pull request closed without merging**
