### PR TITLE
Move to ghcjs8107.

### PR DESCRIPTION
**Pull request by dmjio**
- Use the newly reinstated GHCJS per @falsifian 's work in https://github.com/NixOS/nixpkgs/issues/133271#issue-964150987

- Bump GHC to 8.10.7

### CODE REVIEW

**Comment by smelc** [comment]
Any chance Santa brings this PR to production :santa:? I would love to update GHC in [miso-darkcraw](https://github.com/smelc/miso-darkcraw) :smile_cat:

**Comment by dmjio** [comment]
Hopefully before 2022 it should happen 🎅🏼

**Comment by dmjio** [comment]
@smelc, I think this is ready to go.

**Comment by smelc** [comment]
Thanks @dmjio :pray: I successfully updated [miso-darkcraw](https://github.com/smelc/miso-darkcraw) to use this PR in [this commit](https://github.com/smelc/miso-darkcraw/commit/ef8ec6fc7ed08ff6b0984f87568209c67e72b5ac) :tada:. The update went smoothly, but I have two remarks:

In such a module:

```hs
module Event where

import Data.Aeson -- should be irrelevant to the problem, but is there in my original file
import Data.Text (Text)
import Miso
import Miso.String

f :: Text -> Int
f = undefined
```

The import of `Text` is now deemed redundant with `ghc`. So I initially removed it. Then, compiling with `ghcjs` for shipping, I got `Not in scope: type constructor or class ‘Text’`. I worked around this by using `Data.Text` qualified. Could it be that the exports of `Miso` or `Miso.String` are different when in the `ghc` context and the `ghcjs` context?

My second remark is independent from `miso-darkcraw`. I tried reproducing a part of the `README.md` which failed:

```shell
> git clone https://github.com/dmjio/miso
> cd miso
> git checkout ghcjs8107
> nix-build --arg examples true
... lots of building but ultimately fails with:

Warning: Unknown/unsupported 'ghc' version detected (Cabal 3.2.1.0 supports
'ghc' version < 8.8):
/nix/store/3c08hsjyaj1gq4740p2mpznv7s0cnj41-ghcjs-8.10.7/bin/ghcjs is is based
on GHC version 8.10.7
CallStack (from HasCallStack):
  ...
Setup: Encountered missing or private dependencies:
ghcjs-dom -any, jsaddle -any

error: builder for '/nix/store/h6a5xalbswqmfx31fp64hjknk95ibhpk-entropy-0.4.1.7.drv' failed with exit code 1
error: 1 dependencies of derivation '/nix/store/dgivhviy5b09nq15pb3i9mywzd1wmg3a-websockets-0.12.7.3.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7nrw8wzzfzp2xpirl1ybdi1jp2hii1bs-jsaddle-warp-0.9.8.0.drv' failed to build
building '/nix/store/cc4sp60dy6fq9scx1wq47012gca0zq9h-miso-1.8.1.0.drv'...
error: 1 dependencies of derivation '/nix/store/yjcc159ih8wc14jj5six97bwpkda2pa0-miso-examples-1.8.1.0.drv' failed to build
error: build of '/nix/store/cc4sp60dy6fq9scx1wq47012gca0zq9h-miso-1.8.1.0.drv', '/nix/store/g8frxyqkg31iql1zxvsd47lf5lidv4zq-miso-1.8.1.0.drv', '/nix/store/l1y8pmv69gx388im55ib37mq3hskpbcn-miso-1.8.1.0.drv', '/nix/store/q5bmbpgjjfzdbagdslw1cqfjb9dzdx2p-miso-examples-1.8.1.0.drv', '/nix/store/yjcc159ih8wc14jj5six97bwpkda2pa0-miso-examples-1.8.1.0.drv' failed
```

**Comment by dmjio** [comment]
@smelc Nice catch. Can you try again? Should be fixed now.

**Comment by dmjio** [comment]
Regarding `Text`, while `text` is a boot package, I don't think `Text` is re-exported by `Prelude` yet, so an explicit import is needed I believe.

**Comment by dmjio** [comment]
@smelc 

>  I worked around this by using Data.Text qualified. Could it be that the exports of Miso or Miso.String are different when in the ghc context and the ghcjs context?

You're right, `MisoString` is a synonym for `Text` w/ ghc, and `JSString` w/ ghcjs.

**Comment by smelc** [comment]
Thanks for explaining `MisoString` :pray:

> @smelc Nice catch. Can you try again? Should be fixed now.

I retried `nix-build --arg examples true` on a fresh clone of `master` after the merge and it works now :+1:

**Comment by smelc** [comment]
In the end I reverted [miso-darkcraw](https://github.com/smelc/miso-darkcraw) to use ghc 8.6.5 again, because compilation time with `ghcjs` `8.10.7` were impractical for my feedback loop when debugging UI material :crying_cat_face:

**Pull request merged**
