### PR TITLE
Remove `[View action]` argument from void elements

### PR DESCRIPTION
**Pull request by tysonzero**
#358

### CODE REVIEW

**Comment by dmjio** [comment]
It appears there are breakages on `https://haskell-miso.org` with this change. https://hydra.dmj.io/build/14152/nixlog/2, it seems bulma allows `br` and `hr` tags to contain children.

**Comment by dmjio** [comment]
Let me try to put the children of `hr` and `br` tags as siblings, stay tuned.

**Comment by dmjio** [comment]
Elm actually allows the possibility of child nodes being defined in a `br` tag, despite it not being w3c valid. http://package.elm-lang.org/packages/elm-lang/html/2.0.0/Html#br

**Comment by tysonzero** [comment]
Hmm. I mean if it's not w3c valid doesn't that mean that browsers can implement it however they want (a.k.a undefined behavior)? Assuming that the behavior of such child elements can be relied upon in all browsers then I think it would probably be fine to leave in the ones that are useful. I'm not sure if `Elm` is the best thing to reference since even `img` takes in children when IMO it definitely should not.

**Comment by FPtje** [comment]
I believe Elm's things are generated, or at least a copy paste job. Evan may not have put any thought in it. Judging by [this issue](https://github.com/facebook/react/issues/12396), React forbids void elements to have children. We could do the same. If, hypothetically, a similar issue is created on this repository, we could reply with "there's still `nodeHtml`".

It seems like a good change. It's a breaking change, though. The nice thing here is that we can enforce a HTML rule through the type system.

**Comment by dmjio** [comment]
Added fixes for `haskell-miso.org`, rebased and merged in `6b3734074552476cd179660a79ba0ec6970aa144`

**Pull request closed without merging**
