### PR TITLE
Upgrade nixpkgs to 18.09 and GHCJS to 8.4

### PR DESCRIPTION
**Pull request by puffnfresh**
Sadly this means no GHCJSi but it *should* mean macOS support.

---

Opening this hopefully to help macOS users. No expectation of being merged.

### CODE REVIEW

**Comment by dmjio** [comment]
@puffnfresh thanks for this. And alas, no ghcjsi in sight. A quick hacky script (that is working great) to get "fast" reload functionality is below, might include this in the docs along with latest `nixpkgs` bump. Using `--disable-optimization` makes it pretty snappy. 

```haskell
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE RecordWildCards   #-}
module Main where

import Control.Concurrent
import Control.Concurrent.MVar
import Control.Exception
import Control.Monad
import Data.ByteString.Char8 (pack)
import System.Environment
import System.INotify
import System.FilePath
import System.Directory
import System.Process
import Data.List

data Notify
  = Notify
  { notify :: IO ()
  , wait :: IO ()
  }

-- | Skip channel to model concurrency semantics
-- This ensures that we don't execute more than one command
-- at a time.
initNotify :: IO Notify
initNotify = do
  mvar <- newMVar ()
  pure $
    Notify
      (void $ tryPutMVar mvar ())
      (takeMVar mvar)

main :: IO ()
main = do
  args <- unwords <$> getArgs
  putStrLn "Initializing runner..."
  inotify <- initINotify
  Notify {..} <- initNotify
  dirs <- nub . concat <$> mapM getDirs ["src","test","web"]
  forM_ dirs $ \arg ->
    void $ addWatch inotify [Modify] (pack arg) (const notify)
  forever $ wait >> do
    putStrLn $ "Executing: " ++ args
    callCommand args `catch` (\(e :: SomeException) -> pure ())

getDirs :: FilePath -> IO [FilePath]
getDirs path = do
  isDir <- doesDirectoryExist path
  if isDir
    then do
      dirs <- listDirectory path
      if null dirs
        then pure [path]
        else concat <$> do
          mapM getDirs $ (path </>) <$> dirs
    else pure [prune path]
      where
        prune = reverse . dropWhile (/='/') . reverse

secs :: Int -> Int
secs = (*1000000)
```

**Comment by mtesseract** [comment]
What needs to be done for working GHCJSi?

**Comment by dmjio** [comment]
@mtesseract good question! Let's cc @luite and @Profpatsch. It seems things progressed this far: https://github.com/ghcjs/ghcjs/issues/171. @luite, @Profspatch, how crazy would it be to rebase these changes against the `8.6` branch? Any amount of REPL support would be extremely appreciated. Doesn't even have to integrate with the browser, just something to at least get `ghcid` working would be fantastic. I'd definitely put time into it as well if we had a plan. @luite how far off would you say we are from `ghcjsi` on `8.6`?

**Comment by mtesseract** [comment]
Can confirm: Following the miso README and adding the following modifications produces a working example application:

```
--- default.nix.orig	2019-01-08 09:04:03.000000000 +0100
+++ default.nix	2019-01-08 06:32:51.000000000 +0100
@@ -1,16 +1,16 @@
 { pkgs ? import ((import <nixpkgs> {}).fetchFromGitHub {
     owner = "NixOS";
     repo = "nixpkgs";
-    rev = "a0aeb23";
-    sha256 = "04dgg0f2839c1kvlhc45hcksmjzr8a22q1bgfnrx71935ilxl33d";
+    rev = "b9fa31c";
+    sha256 = "1iqdra7nvcwbydjirjsk71rpzk4ljc0gzqy33fcp8l18y8iwh47k";
   }){}
 }:
 let
   result = import (pkgs.fetchFromGitHub {
-    owner = "dmjio";
+    owner = "puffnfresh";
     repo = "miso";
-    sha256 = "1l1gwzzqlvvcmg70jjrwc5ijv1vb6y5ljqkh7rxxq7hkyxpjyx9q";
-    rev = "95f6bc9b1ae6230b110358a82b6a573806f272c2";
+    sha256 = "1nng214balji3r1f0afh75vkmip1xn66ml8fmg899f6v71yqi307";
+    rev = "1c29116cdc8454337097aee23cbf0bd6744c1d41";
   }) {};
 in pkgs.haskell.packages.ghcjs.callPackage ./app.nix {
   miso = result.miso-ghcjs;
```

**Comment by dmjio** [comment]
Upgrade to `GHCJS` 8.6 is taking place in this PR #493

**Pull request closed without merging**
